# Site settings
description: "PHP Library to export data in various spreadsheet formats like ODS, CSV, TSV ..."
baseurl: "/spreadsheetexport"
url: "http://fusonic.github.io/spreadsheetexport"
github_username: fusonic
github_repository: spreadsheetexport
version: 0.1.1

# Build settings
markdown: kramdown
permalink: pretty
kramdown:
  input: GFM
extensions: [fenced_code_blocks]
sass:
  sass_dir: _sass
  style: :compressed
